# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python3 ./utils/pipeline/Setup.py --install-sdl
    source ./1*/setup-env.sh
  displayName: 'Setup Script'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '-DBUILD_SHADERC=ON -S ..'
    runInsideShell: true
